### ISSUE TITLE
崩溃+年月显示错误

### ISSUE THREAD

**Issue by yangguanghei** [CoderFM/FMCalendar#1]
在FMCalendarData文件中对每年的12月增加了处理逻辑

if currentMonth > 12 {
                currentMonth = currentMonth % 12
                currentYear = year + i / 12 + 1
                
                if currentMonth == 0 {  // 12月的时候需要特殊处理下
                    currentMonth = 12
                    currentYear = year + i / 12
                }
            }

**Comment by CoderFM** [comment]
已经修复了哈，谢谢老铁
